version: "3"

services:
    nginx:
        build:
            context: ./nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./proj:/var/www/html
            - ./logs/nginx:/var/log/nginx
       restart: always
        networks:
            - default

    php-fpm:
        build:
            context: ./php-fpm/7.4
        volumes:
            - ./proj:/var/www/html
            - ./logs/php-fpm:/var/log/php-fpm
        cap_add:
            - SYS_PTRACE
        restart: always
        networks:
            - default

    php-fpm-7.3:
        build:
            context: ./php-fpm/7.3
        volumes:
            - ./proj:/var/www/html
            - ./logs/php-fpm:/var/log/php-fpm
        cap_add:
            - SYS_PTRACE
        restart: always
        networks:
            - default

   mysql:
       build:
           context: ./mysql
       ports:
           - 3306:3306
       volumes:
#           - ./conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
           - ./data.d/mysql:/var/lib/mysql
       restart: always
       networks:
           - default
       environment:
           MYSQL_ROOT_PASSWORD: 123456
           TZ: Asia/Chongqing

   redis:
       image: redis:5.0-alpine
       ports:
           - 6379:6379
       volumes:
           - ./conf.d/redis.conf:/etc/redis.conf:ro
       restart: always
       entrypoint: ["redis-server", "/etc/redis.conf"]
       networks:
           - default

   rabbitmq:
       image: rabbitmq:alpine
       restart: always
       ports:
           - 5672:5672
           - 15672:15672
           - 25672:25672
       environment:
           RABBITMQ_DEFAULT_USER: root
           RABBITMQ_DEFAULT_PASS: 123456
       networks:
           - default
